### PR TITLE
Don't leak env values into `$_SERVER`

### LINKED ISSUE #474: $_SERVER var exposes db_name/user/password and salts
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

When working on a site, I noticed that if I was to `error_log()` the `$_SERVER` variable that the following additional items would be available (name/user/password removed for bug report):
```
[DB_NAME] => {db_name}
[DB_USER] => {user}
[DB_PASSWORD] => {userspwd}
[WP_ENV] => production
[WP_HOME] => https://domain.test
[WP_SITEURL] => https://wp-boilerplate.test/wp
[AUTH_KEY] => generateme
[SECURE_AUTH_KEY] => generateme
[LOGGED_IN_KEY] => generateme
[NONCE_KEY] => generateme
[AUTH_SALT] => generateme
[SECURE_AUTH_SALT] => generateme
[LOGGED_IN_SALT] => generateme
[NONCE_SALT] => generateme
```

## Steps to reproduce

1. Create a local install, use any environment
2. simply `var_dump()` or `error_log()` the `$_SERVER` var
3. See results

**Expected behavior:** These sensitive data shouldn't be available via that variable

**Actual behavior:** These sensitive data shouldn't be able to output

**Reproduces how often:** 100%

## Versions

Bedrock Install: 1.12.8: 2019-09-05
macOS: 10.14.6
laravel/valet 2.3.3

## Additional information

Basic Sage 9 with Bedrocks install on local.

### PR DESCRIPTION
**Pull request by swalkinshaw**
Updates to using a custom repository for `Dotenv` instead of the default which includes `ServerConstAdapter`.

The new custom repository *only* includes `EnvConstAdapter`.

The `$_SERVER` superglobal often gets dumped into logs or into monitoring services so it's better for security to avoid populating it with secrets contained in `.env`.

*Note*: this *could* be a breaking change for some users, but we at least need to ensure it's not breaking in the normal case.

Close #474

### CODE REVIEW

File: config/application.php [hunk 1]
```diff
@@ -29,7 +29,13 @@
  * Use Dotenv to set required environment variables and load .env file in root
  * .env.local will override .env if it exists
  */
-$dotenv = Dotenv\Dotenv::createUnsafeImmutable($root_dir, ['.env', '.env.local'], false);
+$repository = Dotenv\Repository\RepositoryBuilder::createWithNoAdapters()
+    ->addAdapter(Dotenv\Repository\Adapter\EnvConstAdapter::class)
+    ->addAdapter(Dotenv\Repository\Adapter\PutenvAdapter::class)
```
Comment (swalkinshaw) [inline config/application.php:34]: @QWp6t needed this as well to mirror the default behaviour and get everything working

**Comment by montchr** [comment]
Is this still necessary to fix #474?

**Comment by retlehs** [comment]
@montchr I think so! Thanks for the bump, I think this just got forgotten about 😅 will get this rebased and hopefully reviewed soon 

cc @QWp6t @tangrufus

**Comment by Tofandel** [comment]
> Note: this could be a breaking change for some users, but we at least need to ensure it's not breaking in the normal case.

Given that this package doesn't have an upgrade path because it's a boilerplate, I wouldn't worry about breaking changes
